### PR TITLE
Issue7 tablet landscape support

### PR DESCRIPTION
**Pull request by samcorcoran**
This pull request relates to issue #7 and could be merged into that issue .

### CODE REVIEW

**Comment by samcorcoran** [comment]
I have merged master into this branch and fixed a conflict (and added a resulting tweak). Should be ready for an easy merge back into master.

**Comment by tsiemens** [comment]
That's quite a lot, but looks pretty good. Will take a while to review.

My first gripe is your plus and minus layouts. They are basically duplicates.
Instead, please make the layout in layouts/, and get them to use common dimensions in new dimens.xml in values-sw720dp/, etc.

The same goes for character_feats_row.xml
They are the same except for the visibility. You should be able to have an integer constant set to the constant defined by visible or gone.

**Comment by tsiemens** [comment]
Another thing is your changes to the editor fragment layouts. The spinners, etc, are now the only view in the containing linear layouts. This is redundant. You should probably just be able to set the android:layoutGravity property on the spinners to what you have in the linear layout's gravity property to fix it.

**Comment by tsiemens** [comment]
Where you have this 

```
<include
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    layout="@layout/character_combat_stats_plus"/>
```

probably does not require the wrap content. Should be able to be just 

```
<include layout="@layout/character_combat_stats_plus"/>
```

**Comment by tsiemens** [comment]
Some layout issues:
The padding on the left side of the feats row is too small.
I also don't really like the useless views you marked as like "". Please use padding or layout margins instead.

Couple others: 
You forgot to remove some //TODO:Debug log in the feats adapter

Otherwise, this is really awesome. The tablet views are good. And thanks for some of the cleanup.
Also, could you take a look at the nav drawer width? It is covering the whole screen almost in landscape, when it should probably be a fixed dp width.

**Comment by samcorcoran** [comment]
Wow, thank you for such rapid responses! Your suggestions all look really sensible - I'll hopefully get around to them during next week! Let me know if there is anything else.

**Comment by samcorcoran** [comment]
There are two remaining changes I haven't yet done:
1) Spinners in Editor fragments are the sole children in their parent LinearLayout:
I originally did this because the Spinner would otherwise stretch to 50% screenwidth if told to fill_parent. I agree it needs fixing.

While trying to fix this, I realised that android:weightSum can be used here. Setting the android:weightSum="2" on the parent LinearLayout that contains the TextView and the Spinner, and then setting android:weight="1" on the TextView circumvented the problem that Spinners don't accept weights. The result is different, though: the Spinner becomes centred on the screen, and the TextView label sits to the left of it.

I think this is actually _better_ (and is what I originally wanted to do but couldn't work out how), particularly on small screens where the Spinner was being shoved too far right-of-centre.

The downside is that long labels (such as 'Armor Check Penalty:') are forced onto two lines. I personally think this still looks fine, especially with the increased vertical padding between fields that I recently added. What do you think?

2) 'Null entries' to create an 'empty row' in armor row and weapon row columns need to be replaced with padding or margins

I think adding paddingTop to the column would be a sensible alternative. The height of this padding needs to be the exact height that a LinearLayout would take up (which is why I added that null entry - to recreate that exact height). 

Do you know how I can specify the paddingTop to be '1 line height'?

3) I still need to take a look at the nav drawer, but I see the problem you mean. Should be an easy fix.

**Comment by tsiemens** [comment]
The layouts seem fine now, so I'll just wait for the nav drawer changes. I also noticed that the add button on spells becomes ridiculously wide when in landscape. Maybe have a look at that as well. It doesn't happen on inventory though.

**Comment by samcorcoran** [comment]
I have set a fixed width of 300dp on the nav drawer, which provides plenty of room for the text and offers some blank space on the right too, whilst still being small enough to fit on small phone screens. It would have been nice to do this by wrapping the drawer width to the content, but no attempts at this were successful.

I fixed the spellbook addSpell button's limitless expansion, so now it occupies 2/15 of the screen width, just like the inventory ui equivalent button does.

There were two other large changes I made:
1) I used weight sums to center the entry fields and spinners on the editor fragments. I believe this looks nicer, and the user's eye is drawn more rapidly to the various numbers and other entries, rather than to the list of labels. This approach give a balanced and consistent look across all screen sizes. These changes also got rid of the pointless LinearLayouts around the spinners which I had added. 

2) I prevented the larger editor fragment text fields (e.g. item name, item special properties, feat description etc etc) from stretching to the full width of the screen. On large screens the various fields were center aligned (even before my changes in [1]) which meant that a left-gravity item name was way too far off to the side to look sensible. Fields such as item name, feat name etc have a minimum width, and will also stretch wider up to a specified maximum (though I doubt most item names will need much room - another reason not to have gigantic fields!). These fields now also centralised their text, so they now feel more like titles. Fields such as Item description, spell description follow the same principle, but are slightly larger for both min and max dimensions. Their text remains left aligned, centralised large blocks of text will feel less comfortable to the user.

There were a few other small fixes too.

I think that concludes all of my changes and your changes for large/landscape layouts. Let me know if you have any other comments/suggestions, otherwise I'd say it's ready to merge in!

**Comment by tsiemens** [comment]
Great work! Approved for merge.

**Pull request merged**
